services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - be

  be:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - be
    depends_on:
      db:
        condition: service_healthy

volumes:
  test-db-data:

networks:
  be:
    driver: bridge